api_platform:
  mapping:
    paths:  ['%kernel.project_dir%/src/Entity']

  collection:
    pagination:
      items_per_page_parameter_name: 'count'
  defaults:
    pagination_client_enabled: true
    pagination_enabled: true
    pagination_items_per_page: 10
    pagination_client_items_per_page: true